[package]
name = "crypto-pure"
version = "0.0.9"
authors = ["Taylor Barrella <tbarrella@gmail.com>"]
edition = "2018"

[dependencies]
byteorder = { version = "1.2.6", default-features = false, features = ["i128"] }

[features]
default = ["std"]
std = []
