[package]
name = "crypto-pure"
version = "0.0.9"
authors = ["Taylor Barrella <tbarrella@gmail.com>"]

[dependencies]
byteorder = { version = "1.2.3", default-features = false, features = ["i128"] }

[features]
default = ["std"]
std = []
