[package]
name = "crypto-pure"
version = "0.0.9"
authors = ["Taylor Barrella <tbarrella@gmail.com>"]

[dependencies]
byteorder = { version = "1.1.0", default-features = false }

[features]
default = ["std"]
std = []
